# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDfI2NNq_WgV40aRQgp-sDMAXYR4Fd3E
"""

mark1 = float(input("Enter marks for subject 1: "))
mark2 = float(input("Enter marks for subject 2: "))
mark3 = float(input("Enter marks for subject 3: "))

total = mark1 + mark2 + mark3
average = total / 3

print(f"Total Marks: {total}")
print(f"Average Marks: {average}")

student_record = {
    "Name": "Sazni",
    "Age": 18,
    "Course": "Computer Science"
}

print("--- Student Record ---")
print(f"Student Name:{student_record['Name']}")
print(f"Student Age:{student_record['Age']}")
print(f"Course:{student_record['Course']}")

try:
  num = int(input("Enter a number: "))
  print(f"You have entered: {num}")
except ValueError:
  print("Please enter a number!")

def input_marks():
  m01 = int(input("Enter Marks-01: "))
  m02 = int(input("Enter Marks-02: "))
  m03 = int(input("Enter Marks-03: "))
  return m01,m02,m03

def calc_total(m01,m02,m03):
  return m01+m02+m03

def calc_avg(total_marks):
  return total_marks/3

def print_report(name,total,average):
  print("\n-------Marks Report-------")
  print(f"Name: {name} \nTotal: {total} \nAverage: {average}")

student_name = input("Enter Your Name: ")
m01,m02,m03 = input_marks()
total = calc_total(m01,m02,m03)
average = calc_avg(total)
print_report(student_name,total,average)

def get_grade(average):
  if average >= 75:
    return "A"
  elif average >= 65:
    return "B"
  elif average >= 55:
    return "C"
  elif average >= 35:
    return "S"
  else:
    return "F"

avg_marks = float(input("Enter Your Average Marks: "))
final_grade = get_grade(avg_marks)

print(f"Your Grade Is: {final_grade}")

def create_shopping_list():
  shoppinglist = []

  for i in range(5):
    item = input(f"Enter Item {i+1}:")
    shoppinglist.append(item)
  return shoppinglist

my_list = create_shopping_list()
print("\n--------Shopping List--------")
for item in my_list:
  print(f"- {item}")

def create_student_record():
  name = input("Enter Student Name: ")
  age = input("Enter Student Age: ")
  course = input("Enter Student Course: ")

  record = {
      "Name": name,
      "Age": age,
      "Course": course
  }
  return record

student = create_student_record()
print("\n--- Student Record ---")
print(f"Name: {student['Name']}")
print(f"Age: {student['Age']}")
print(f"Course: {student['Course']}")

def withdraw_money(current_balance, amount):
    # Check if the amount is greater than zero
    if amount <= 0:
        return "Invalid amount. Please enter a value greater than 0.", current_balance

    # Check if there are enough funds
    if amount > current_balance:
        return "Insufficient funds!", current_balance

    # Perform the withdrawal
    new_balance = current_balance - amount
    return f"Withdrawal successful! You withdrew ${amount}.", new_balance

# --- Example Usage ---
balance = 1000  # Starting balance
withdraw_amt = 250

message, balance = withdraw_money(balance, withdraw_amt)

print(message)
print(f"Current Balance: ${balance}")

try:
    my_balance = 500.0
    requested = float(input("How much would you like to withdraw? "))

    msg, my_balance = withdraw_money(my_balance, requested)
    print(msg)
    print(f"Remaining Balance: ${my_balance}")

except ValueError:
    print("Error: Please enter a valid number (e.g., 50.00)")

customerbalance = 10000

def mainMenu():
  print("1. Cash Withdraw\n2. Cash Deposit\n3. Balance\n4. Exit")

def withdraw():
  global customerbalance
  withdrawmoney = int(input("How much: "))
  if withdrawmoney <= customerbalance:
    customerbalance = customerbalance - withdrawmoney
    print("Withdrawn: Rs. ",withdrawmoney)
    print("Available Balance: Rs. ",customerbalance)

def deposit():
  global customerbalance
  depositmoney = int(input("How much: "))
  customerbalance = customerbalance - depositmoney
  print("Deposited: Rs. ",depositmoney)
  print("Available Balance: Rs. ",customerbalance)

def balance():
  global balance
  print("Available Balance: Rs. ",customerbalance)

program = True
while program:
  mainMenu()
  userchoice = input("Enter Choice: ")
  if userchoice == "1":
    withdraw()
  elif userchoice == "2":
    deposit()
  elif userchoice == "3":
    balance()
  elif userchoice == "4":
    confirmchoice = input("Do you want to exit? (y/n): ")
    if confirmchoice == "y":
      program = False
      break
    else:
      print("returning to menu...")
  else:
    print("Invalid, Please Try Again!")







def movie_ticketing_system():
    print("=== WELCOME TO SLIIT TICKETING ===")
    username = input("Enter username: ").strip()
    password = input("Enter password: ").strip()

    if not username or not password:
        print("Invalid login credentials. Exiting system.")
        return

    print(f"\nLogin successful! Welcome, {username}.\n")

    movies = {
        1: {"title": "Leo 2", "price": 12.00, "seats": 50},
        2: {"title": "Spiderman", "price": 9.50, "seats": 30},
        3: {"title": "Hang Over", "price": 11.00, "seats": 20},
        4: {"title": "Avengers", "price": 8.00, "seats": 45}
    }

    grand_total = 0.0
    booked_tickets = {}

    while True:
        print("--- MAIN MENU ---")
        print("Available Movies:")
        print(f"{'ID':<5} {'Movie Title':<25} {'Price':<10} {'Available Seats':<15}")
        print("-" * 55)

        for movie_id, info in movies.items():
            print(f"{movie_id:<5} {info['title']:<25} ${info['price']:<9.2f} {info['seats']:<15}")

        print("-" * 55)
        print("5. Exit & View Total Bill")
        print("-" * 55)

        choice = input("Select a movie ID (1-4) or 5 to exit: ").strip()

        if choice == '5':
            break

        if not choice.isdigit() or int(choice) not in movies:
            print("\n[!] Invalid selection. Please choose a valid option.\n")
            continue

        selected_id = int(choice)
        movie = movies[selected_id]

        try:
            seats_to_book = int(input(f"How many seats for '{movie['title']}'? "))
        except ValueError:
            print("\n[!] Please enter a valid number.\n")
            continue

        if seats_to_book <= 0:
            print("\n[!] You must book at least 1 seat.\n")
            continue

        if seats_to_book > movie['seats']:
            print(f"\n[!] Sorry, only {movie['seats']} seats are available for this movie.\n")
            continue

        movie['seats'] -= seats_to_book

        cost = seats_to_book * movie['price']
        grand_total += cost


        title = movie["title"]
        if title in booked_tickets:
            booked_tickets[title]["seats"] += seats_to_book
            booked_tickets[title]["cost"] += cost
        else:
            booked_tickets[title] = {
                "seats": seats_to_book,
                "cost": cost
            }

        print(f"\n[✓] Successfully selected {seats_to_book} seat(s)!")
        print(f"Current Booking Amount: ${cost:.2f}\n")

    print("\n=====================================")
    print("          FINAL RECEIPT              ")
    print("=====================================")
    if not booked_tickets:
        print("No tickets booked during this session.")
    else:

        for title, details in booked_tickets.items():
            print(f"• {title} x{details['seats']} : ${details['cost']:.2f}")
        print("-" * 37)
        print(f"GRAND TOTAL TO PAY: ${grand_total:.2f}")
    print("=====================================")
    print("Thank you for using Sliit Ticketing!")


if __name__ == "__main__":
    movie_ticketing_system()

